# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - make bin
      - go build -o bin/mactools mactools.go 

  run:
    cmds:
      - ./bin/mactools
  
  test:
    cmds:
      - go test -v ./...


  
